export const quotes = [
    "You don't have to control your thoughts. You just have to stop letting them control you.",
    "Peace begins with a deep breath.",
    "It's okay to feel. Let it pass through you.",
    "Healing is not linear.",
    "Breathe. You’re doing the best you can.",
    "Small steps every day add up to big change.",
    "You are more than your thoughts.",
    "Let go of what you can't control.",
    "You are allowed to rest.",
    "Your feelings are valid.",
    "Be gentle with yourself.",
    "This too shall pass.",
    "Every day is a fresh start.",
    "Progress, not perfection.",
    "It’s okay to ask for help.",
    "You are not alone.",
    "Take it one breath at a time.",
    "Rest is productive.",
    "Trust the timing of your journey.",
    "One moment at a time.",
    "You are doing better than you think.",
    "Feel it to heal it.",
    "Give yourself permission to feel.",
    "Honor your emotions.",
    "Storms don't last forever.",
    "Keep going, you’re growing.",
    "Your mind deserves peace too.",
    "Be proud of how far you’ve come.",
    "You’re trying and that’s enough.",
    "You are not your anxiety.",
    "Growth happens in the quiet.",
    "Your pace is perfect.",
    "Let today be enough.",
    "You deserve kindness — even from yourself.",
    "The sky is still blue above the clouds.",
    "You’ve made it through tough days before.",
    "You are strong enough to keep going.",
    "Healing starts with awareness.",
    "Listen to what your body is saying.",
    "Self-care isn’t selfish.",
    "It's okay to not be okay.",
    "You’ve got this.",
    "Don’t rush your healing.",
    "Give yourself credit.",
    "This feeling is temporary.",
    "Light exists even in darkness.",
    "You are a work in progress, and that’s okay.",
    "Choose peace over perfection.",
    "You’re learning every day.",
    "Trust your inner wisdom.",
    "You’re allowed to pause.",
    "Self-love is a journey.",
    "Every emotion has a message.",
    "Be curious, not judgmental.",
    "Even a slow start is a start.",
    "Embrace the ebb and flow.",
    "Find calm in the chaos.",
    "Your path is yours alone.",
    "You have the power to shift your thoughts.",
    "Compassion is a superpower.",
    "This moment is enough.",
    "You’re not behind. You’re on your way.",
    "Let your breath guide you.",
    "Take space when you need it.",
    "It's brave to feel deeply.",
    "You are worthy of peace.",
    "Recharging is necessary.",
    "Take time to nourish your soul.",
    "Notice what feels good.",
    "Create room for calm.",
    "Self-acceptance changes everything.",
    "Speak kindly to yourself.",
    "The smallest step is still a step.",
    "Stillness is strength.",
    "You don’t need to have it all figured out.",
    "You are capable and resilient.",
    "Let go of what weighs you down.",
    "Focus on what you can control.",
    "You are not your worst day.",
    "There’s beauty in slowing down.",
    "Let kindness be your compass.",
    "You matter more than you know.",
    "One breath at a time, one step at a time.",
    "Your story isn’t over.",
    "You deserve to feel seen.",
    "Peace lives in the present.",
    "Emotions are not enemies.",
    "Let your heart lead with softness.",
    "The sun always rises.",
    "Feelings aren't facts.",
    "You’re allowed to feel joy.",
    "Gentleness is powerful.",
    "Slow down and just be.",
    "The present moment is a gift.",
    "You are your safe space.",
    "Keep showing up for yourself.",
    "You’re not too much — you’re enough.",
    "The universe is rooting for you.",
    "Celebrate your tiny victories.",
    "There is light in you.",
    "Take time to exhale.",
    "Your calm is contagious.",
    "You are growing through what you’re going through.",
  ];